# Generated by Django 5.0.6 on 2025-01-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_city_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='animals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='colors',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='city',
            name='texts',
            field=models.BooleanField(default=False),
        ),
    ]
