# Generated by Django 5.0.6 on 2025-01-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_city_animals_city_colors_city_texts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='animals',
        ),
        migrations.RemoveField(
            model_name='city',
            name='texts',
        ),
    ]
